// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALvPmEB7bhzanhWsQDbfwGAdu-zwow7dg',
    appId: '1:551998120038:web:c2413d00338ef8c5c78da7',
    messagingSenderId: '551998120038',
    projectId: 'dailyplanner-7bcd0',
    authDomain: 'dailyplanner-7bcd0.firebaseapp.com',
    storageBucket: 'dailyplanner-7bcd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKIWzA4u5HIXgy2yAuvptcPX6BfzP3T1c',
    appId: '1:551998120038:android:f5e93cd6c7c4aae2c78da7',
    messagingSenderId: '551998120038',
    projectId: 'dailyplanner-7bcd0',
    storageBucket: 'dailyplanner-7bcd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHYdTf8gRjAG80pCiPhxgenRqJn2Scy8',
    appId: '1:551998120038:ios:d848ddcac2349550c78da7',
    messagingSenderId: '551998120038',
    projectId: 'dailyplanner-7bcd0',
    storageBucket: 'dailyplanner-7bcd0.appspot.com',
    iosBundleId: 'com.example.dailyPlannerTest',
  );
}
